#@ load("@ytt:data", "data")
#@ if data.values.project_pacific:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harbor-setup
  namespace: harbor-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: Group
  name: system:serviceaccounts
#@ end
