---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-setup-bash
  namespace: harbor-setup
data:
  harbor-setup.sh: |
    #!/bin/bash
    set -x
    
    NSENTER="/usr/bin/nsenter -t 1 -m -u -n -i --"
    
    HEAD=`cat /tmp/harbor-cert | head -2 | sed 1d`
    ${NSENTER} grep -q ${HEAD} /etc/pki/tls/certs/ca-bundle.crt || {
    
      ${NSENTER} cp /etc/pki/tls/certs/ca-bundle.crt /tmp/
      cat /tmp/harbor-cert  >> /host/ca-bundle.crt
    
      ${NSENTER} cp /tmp/ca-bundle.crt /etc/pki/tls/certs/ca-bundle.crt
      ${NSENTER} systemctl -a | grep -q docker.service && { 
        ${NSENTER} systemctl restart docker.service
        ${NSENTER} systemctl status docker.service
      }
      ${NSENTER} systemctl -a | grep -q containerd.service && { 
        ${NSENTER} systemctl restart containerd.service
        ${NSENTER} systemctl status containerd.service
      }
    }
    while true; do
     sleep 3600
    done
