#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name:  harbor-registry
  namespace: harbor-setup
type: generic
data:
  root-certificate.txt: #@ base64.encode(data.values.ca_cert_data)
